version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: task-tracker-db
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 95751535
      POSTGRES_DB: task-tracker
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SPRING_DATASOURCE_USERNAME} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
  task-tracker:
    build: .
    container_name: task-tracker-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/task-tracker
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 95751535

volumes:
  db-data: