spring.datasource:
  url: jdbc:postgresql://db:5432/task-tracker
  username: admin
  password: 95751535

flyway:
  enabled: true
  locations: classpath:db/migration


logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.boot: DEBUG

debug: true